/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab06;

import com.google.common.annotations.VisibleForTesting;

public class Rectangle {

    public int getX() { return 0; }
    public int getY() { return 0; }
    public int getWidth() { return 1; }
    public int getHeight() { return 1; }

}
