/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab04;

import org.apache.commons.math3.geometry.spherical.oned.ArcsSet;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
import java.util.stream.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;

class SplittingTest {

    @Test
    void testNullArray() {
        assertFalse(Splitting.canBalance(null));
    }

    @Test
    void testLengthOneArray() {
        assertFalse(Splitting.canBalance(new int[]{1}));
    }

    @Test
    void testOddSum() {
        assertFalse(Splitting.canBalance(new int[]{1, 2}));
    }

    @Test
    void testCanBalanceTrue() {
        assertTrue(Splitting.canBalance(new int[]{1, 1}));
    }

    @Test
    void testCannotBalanceEvenSum() {
        assertFalse(Splitting.canBalance(new int[]{2, 1, 1, 2, 1}));
    }
}
