/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


import java.util.Arrays;

class RectangleTest {
    @Test
    void testHarnessWorking() {
        assertTrue(true);
    }

    @Test
    void createDefaultRect() {
        Rectangle r = new Rectangle();
        assertEquals(1, r.getWidth());
        assertEquals(1, r.getHeight());
        assertEquals(0, r.getX());
        assertEquals(0, r.getY());
    }
}
